name: Go

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Test
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Run integration tests
        run: make test_integration
        env:
          TOKEN: ${{ secrets.TOKEN }}
          TEST_CHAT_ID: ${{ secrets.TEST_CHAT_ID }}
          TEST_USER_ID: ${{ secrets.TEST_USER_ID }}

  golangci-lint:
    name: Lint
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.37
          skip-go-installation: true
